### ISSUE TITLE
Register Page

### ISSUE THREAD

**Issue by vleango** [vleango/famoustitle#1]
Add a register page for new users (register should allow users to do functions such as saving articles)

**User schema:**
- id
- email
- password
- first_name
- last_name
- access: [ { provider: 'facebook', token: '123'}, { provider: 'web', token: '456'} ]
- admin? (default to false)

**Tasks:**
- [x] Create Component
- [x] Wire-up with Redux
- [x] Add Register function to lambda-go
- [x] Implement Register function
